# Ex 2 — Working with Pandas

**Dataset:** fanspeed.csv  
**Reg No:** URK24CS1021

In [1]:
print("URK24CS1021")

import pandas as pd

df = pd.read_csv("fanspeed.csv")
df

URK24CS1021

    Temperature  Observed Fan Speed
0      5.000000           22.483571
1      5.303030           19.914739
2      5.606061           24.450564
3      5.909091           29.433331
4      6.212121           21.253476
..          ...                 ...
95    33.787879          104.046062
96    34.090909          113.753329
97    34.393939          114.487094
98    34.696970          114.116476
99    35.000000          113.827064

[100 rows x 2 columns]

In [2]:
print("URK24CS1021")

df.head(10)

URK24CS1021

   Temperature  Observed Fan Speed
0     5.000000           22.483571
1     5.303030           19.914739
2     5.606061           24.450564
3     5.909091           29.433331
4     6.212121           21.253476
5     6.515152           21.859618
6     6.818182           31.532428
7     7.121212           28.079598
8     7.424242           22.501113
9     7.727273           28.167346

In [3]:
print("URK24CS1021")

df.tail(8)

URK24CS1021

    Temperature  Observed Fan Speed
92    32.878788          105.126098
93    33.181818          107.907144
94    33.484848          108.494005
95    33.787879          104.046062
96    34.090909          113.753329
97    34.393939          114.487094
98    34.696970          114.116476
99    35.000000          113.827064

In [4]:
print("URK24CS1021")

df.shape, list(df.columns), df.dtypes

URK24CS1021

((100, 2), ['Temperature', 'Observed Fan Speed'], Temperature           float64
Observed Fan Speed    float64
dtype: object)

In [5]:
print("URK24CS1021")

df.describe()

URK24CS1021

       Temperature  Observed Fan Speed
count   100.000000          100.000000
mean     20.000000           66.568646
std       8.791361           30.065419
min       5.000000           18.312387
25%      12.500000           39.894309
50%      20.000000           69.669067
75%      27.500000           93.760259
max      35.000000          114.487094

In [6]:
print("URK24CS1021")

demo = df.copy()
demo.loc[[3, 27, 61], "Observed Fan Speed"] = None
demo.isnull().sum()

URK24CS1021

Temperature           0
Observed Fan Speed    3
dtype: int64

In [7]:
print("URK24CS1021")

demo["Observed Fan Speed"] = demo["Observed Fan Speed"].fillna(demo["Observed Fan Speed"].mean())
demo.isnull().sum()

URK24CS1021

Temperature           0
Observed Fan Speed    0
dtype: int64

In [8]:
print("URK24CS1021")

df.loc[5:8, ["Temperature"]]

URK24CS1021

   Temperature
5     6.515152
6     6.818182
7     7.121212
8     7.424242

In [9]:
print("URK24CS1021")

df[df["Temperature"] > 25].head()

URK24CS1021

    Temperature  Observed Fan Speed
67    25.303030           90.926755
68    25.606061           88.626362
69    25.909091           84.501674
70    26.212121           90.443342
71    26.515152           97.235637

In [10]:
print("URK24CS1021")

df["Speed_Per_Degree"] = df["Observed Fan Speed"] / df["Temperature"]
df["Speed_Level"] = df["Observed Fan Speed"].apply(lambda x: "High" if x > 60 else "Low")
df.head()

URK24CS1021

   Temperature  Observed Fan Speed  Speed_Per_Degree Speed_Level
0     5.000000           22.483571          4.496714         Low
1     5.303030           19.914739          3.755351         Low
2     5.606061           24.450564          4.361452         Low
3     5.909091           29.433331          4.981025         Low
4     6.212121           21.253476          3.421291         Low

In [11]:
print("URK24CS1021")

df.sort_values("Observed Fan Speed", ascending=False).head()

URK24CS1021

    Temperature  Observed Fan Speed  Speed_Per_Degree Speed_Level
97    34.393939          114.487094          3.328700        High
98    34.696970          114.116476          3.288946        High
99    35.000000          113.827064          3.252202        High
96    34.090909          113.753329          3.336764        High
91    32.575758          112.570498          3.455652        High

In [12]:
print("URK24CS1021")

df.groupby("Speed_Level")["Observed Fan Speed"].mean()

URK24CS1021

Speed_Level
High    88.332559
Low     35.249845
Name: Observed Fan Speed, dtype: float64

In [13]:
print("URK24CS1021")

df["Rank_dense"] = df["Observed Fan Speed"].rank(method="dense")
df.sort_values("Rank_dense").head()

URK24CS1021

    Temperature  Observed Fan Speed  Speed_Per_Degree Speed_Level  Rank_dense
13     8.939394           18.312387          2.048504         Low         1.0
14     9.242424           19.860259          2.148815         Low         2.0
1      5.303030           19.914739          3.755351         Low         3.0
4      6.212121           21.253476          3.421291         Low         4.0
5      6.515152           21.859618          3.355197         Low         5.0